"""phase1 nodes gpus metrics allocations containers

Revision ID: c94a7bea2551
Revises: 5b51ca5bb241
Create Date: 2026-08-08 06:44:50.250345

Every migration must implement a working ``downgrade``. ``make migrate-roundtrip``
runs upgrade -> downgrade -> upgrade in CI, so an unimplemented downgrade fails the
build rather than being discovered during a rollback at 3am.

Phase 1 baseline: the eight tables owned by M04/M05/M06.

    nodes                 managed hosts running the node agent
    gpus                  physical GPUs, keyed on hardware UUID
    gpu_metrics           telemetry samples — the platform's largest table
    gpu_processes         current occupancy, replaced wholesale per cycle
    gpu_health_events     health transitions, recorded on change only
    gpu_allocations       GPU reservations — see below
    containers            cached container inventory per node

Autogenerated, then reviewed by hand. Confirmed in review:

* **The partial unique index survived autogenerate.** ``uq_gpu_allocations_active``
  carries ``postgresql_where=released_at IS NULL``, which is the whole point: a plain
  UNIQUE(node_id, gpu_index) would forbid ever reusing a GPU after release, while no
  index at all lets two concurrent deployments both claim GPUs 0 and 1 — the first
  vLLM container wins and the second dies with a CUDA OOM that reads like a model bug.
  Autogenerate does not reliably preserve partial-index predicates, so this was checked
  against ``pg_indexes`` rather than assumed.
* ``nodes.agent_token_encrypted`` is Fernet ciphertext under SECURITY__ENCRYPTION_KEY,
  not a hash. The platform *presents* this token rather than verifying one, so a hash
  would be unusable; encryption keeps the property that matters — the key lives outside
  the database, so a dump alone does not yield control of every managed host.
* ``gpus`` is unique on ``uuid`` (hardware identity), not ``index``: an index is
  reassigned when a card moves slots, and keying on it would merge two devices' metric
  history.
* ``gpu_metrics`` and ``gpu_processes`` use bigserial primary keys rather than UUIDs. At
  ~700k rows/month/node, 16 extra bytes per row buys nothing any query uses.
* ECC counters are nullable with no default: a device that does not report ECC must not
  be recorded as a device reporting zero errors.
* Everything cascades from ``nodes``. ``acknowledged_by`` and ``reserved_by`` are
  SET NULL — deleting a user must not erase the record of what happened.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c94a7bea2551"
down_revision: str | None = "5b51ca5bb241"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nodes",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("agent_url", sa.String(length=512), nullable=False),
        sa.Column("agent_token_encrypted", sa.Text(), nullable=False),
        sa.Column("agent_version", sa.String(length=32), nullable=True),
        sa.Column("agent_verify_tls", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("status_detail", sa.Text(), nullable=True),
        sa.Column("os_info", sa.String(length=255), nullable=True),
        sa.Column("kernel_version", sa.String(length=255), nullable=True),
        sa.Column("architecture", sa.String(length=32), nullable=True),
        sa.Column("cpu_model", sa.String(length=255), nullable=True),
        sa.Column("cpu_cores", sa.Integer(), nullable=True),
        sa.Column("memory_total_mib", sa.Integer(), nullable=True),
        sa.Column("docker_version", sa.String(length=64), nullable=True),
        sa.Column("nvidia_runtime_available", sa.Boolean(), nullable=False),
        sa.Column("nvidia_driver_version", sa.String(length=64), nullable=True),
        sa.Column("cuda_version", sa.String(length=32), nullable=True),
        sa.Column("gpu_probe", sa.String(length=32), nullable=True),
        sa.Column("gpu_synthetic", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('GPU', 'CPU')", name=op.f("ck_nodes_role_valid")),
        sa.CheckConstraint(
            "status IN ('ONLINE', 'OFFLINE', 'DEGRADED', 'UNKNOWN')",
            name=op.f("ck_nodes_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
    )
    op.create_index(op.f("ix_nodes_name"), "nodes", ["name"], unique=True)
    op.create_index(op.f("ix_nodes_status"), "nodes", ["status"], unique=False)
    op.create_table(
        "containers",
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("container_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("image", sa.String(length=512), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("status_text", sa.String(length=255), nullable=True),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ports", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("managed", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["node_id"], ["nodes.id"], name=op.f("fk_containers_node_id_nodes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_containers")),
        sa.UniqueConstraint("node_id", "container_id", name="node_container"),
    )
    op.create_index(op.f("ix_containers_managed"), "containers", ["managed"], unique=False)
    op.create_index("ix_containers_node_state", "containers", ["node_id", "state"], unique=False)
    op.create_table(
        "gpus",
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("memory_total_mib", sa.Integer(), nullable=False),
        sa.Column("driver_version", sa.String(length=64), nullable=True),
        sa.Column("cuda_version", sa.String(length=32), nullable=True),
        sa.Column("pci_bus_id", sa.String(length=64), nullable=True),
        sa.Column("nvlink_peers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["node_id"], ["nodes.id"], name=op.f("fk_gpus_node_id_nodes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gpus")),
        sa.UniqueConstraint("node_id", "index", name="node_index"),
        sa.UniqueConstraint("uuid", name="uuid"),
    )
    op.create_index(op.f("ix_gpus_uuid"), "gpus", ["uuid"], unique=False)
    op.create_table(
        "gpu_allocations",
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("gpu_index", sa.Integer(), nullable=False),
        sa.Column("gpu_id", sa.UUID(), nullable=True),
        sa.Column("reservation_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.String(length=255), nullable=False),
        sa.Column(
            "reserved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reserved_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gpu_id"],
            ["gpus.id"],
            name=op.f("fk_gpu_allocations_gpu_id_gpus"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
            name=op.f("fk_gpu_allocations_node_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reserved_by"],
            ["users.id"],
            name=op.f("fk_gpu_allocations_reserved_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gpu_allocations")),
    )
    op.create_index(
        "ix_gpu_allocations_node_active",
        "gpu_allocations",
        ["node_id", "released_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gpu_allocations_reservation_id"),
        "gpu_allocations",
        ["reservation_id"],
        unique=False,
    )
    op.create_index(
        "uq_gpu_allocations_active",
        "gpu_allocations",
        ["node_id", "gpu_index"],
        unique=True,
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.create_table(
        "gpu_health_events",
        sa.Column("gpu_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("previous_severity", sa.String(length=16), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "severity IN ('HEALTHY', 'WARNING', 'CRITICAL', 'UNKNOWN')",
            name=op.f("ck_gpu_health_events_severity_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"],
            ["users.id"],
            name=op.f("fk_gpu_health_events_acknowledged_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["gpu_id"],
            ["gpus.id"],
            name=op.f("fk_gpu_health_events_gpu_id_gpus"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gpu_health_events")),
    )
    op.create_index(
        "ix_gpu_health_events_gpu_occurred",
        "gpu_health_events",
        ["gpu_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gpu_health_events_occurred_at"), "gpu_health_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "gpu_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gpu_id", sa.UUID(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("utilization_percent", sa.Float(), nullable=False),
        sa.Column("memory_used_mib", sa.Integer(), nullable=False),
        sa.Column("memory_total_mib", sa.Integer(), nullable=False),
        sa.Column("temperature_celsius", sa.Float(), nullable=False),
        sa.Column("power_draw_watts", sa.Float(), nullable=False),
        sa.Column("power_limit_watts", sa.Float(), nullable=True),
        sa.Column("sm_clock_mhz", sa.Integer(), nullable=True),
        sa.Column("sm_utilization_percent", sa.Float(), nullable=True),
        sa.Column("ecc_errors_corrected", sa.Integer(), nullable=True),
        sa.Column("ecc_errors_uncorrected", sa.Integer(), nullable=True),
        sa.Column("pcie_replay_counter", sa.Integer(), nullable=True),
        sa.Column("nvlink_bandwidth_mbps", sa.Float(), nullable=True),
        sa.Column("health", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["gpu_id"], ["gpus.id"], name=op.f("fk_gpu_metrics_gpu_id_gpus"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gpu_metrics")),
    )
    op.create_index(
        "ix_gpu_metrics_gpu_recorded", "gpu_metrics", ["gpu_id", "recorded_at"], unique=False
    )
    op.create_index("ix_gpu_metrics_recorded_at", "gpu_metrics", ["recorded_at"], unique=False)
    op.create_table(
        "gpu_processes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gpu_id", sa.UUID(), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("process_name", sa.String(length=255), nullable=False),
        sa.Column("used_memory_mib", sa.Integer(), nullable=False),
        sa.Column("container_id", sa.String(length=64), nullable=True),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gpu_id"], ["gpus.id"], name=op.f("fk_gpu_processes_gpu_id_gpus"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gpu_processes")),
    )
    op.create_index("ix_gpu_processes_gpu", "gpu_processes", ["gpu_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_gpu_processes_gpu", table_name="gpu_processes")
    op.drop_table("gpu_processes")
    op.drop_index("ix_gpu_metrics_recorded_at", table_name="gpu_metrics")
    op.drop_index("ix_gpu_metrics_gpu_recorded", table_name="gpu_metrics")
    op.drop_table("gpu_metrics")
    op.drop_index(op.f("ix_gpu_health_events_occurred_at"), table_name="gpu_health_events")
    op.drop_index("ix_gpu_health_events_gpu_occurred", table_name="gpu_health_events")
    op.drop_table("gpu_health_events")
    op.drop_index(
        "uq_gpu_allocations_active",
        table_name="gpu_allocations",
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.drop_index(op.f("ix_gpu_allocations_reservation_id"), table_name="gpu_allocations")
    op.drop_index("ix_gpu_allocations_node_active", table_name="gpu_allocations")
    op.drop_table("gpu_allocations")
    op.drop_index(op.f("ix_gpus_uuid"), table_name="gpus")
    op.drop_table("gpus")
    op.drop_index("ix_containers_node_state", table_name="containers")
    op.drop_index(op.f("ix_containers_managed"), table_name="containers")
    op.drop_table("containers")
    op.drop_index(op.f("ix_nodes_status"), table_name="nodes")
    op.drop_index(op.f("ix_nodes_name"), table_name="nodes")
    op.drop_table("nodes")
    # ### end Alembic commands ###
