"""phase2 model registry deployments aliases api keys usage

Revision ID: 59d310bc136b
Revises: c94a7bea2551
Create Date: 2026-08-08 07:40:51.609951

Every migration must implement a working ``downgrade``. ``make migrate-roundtrip``
runs upgrade -> downgrade -> upgrade in CI, so an unimplemented downgrade fails the
build rather than being discovered during a rollback at 3am.

Phase 2 baseline: the seven tables owned by M07/M08/M09 (+ minimal M20).

    models, model_files          the local catalogue and its verified contents
    model_deployments            a model being served on a node (§M08 lifecycle)
    model_aliases                stable public names (§13)
    api_clients, api_keys        gateway credentials
    usage_records                per-call accounting

Autogenerated, then reviewed by hand. Confirmed in review:

* ``model_deployments.model_id`` is ON DELETE **RESTRICT**, unlike almost every other FK
  here. Deleting a model that is still serving traffic must be refused, not silently
  orphan a running container on some node.
* ``model_deployments.reservation_id`` is a plain UUID rather than an FK to
  gpu_allocations: one deployment holds *several* allocation rows sharing that id, so an
  FK would need a composite key for no benefit. The reservation is taken in the same
  transaction as the deployment, so the two commit or roll back together (§9).
* ``api_keys.key_hash`` is UNIQUE — it is the gateway's lookup key on every inference
  request, which is also why keys are SHA-256 rather than argon2.
* ``usage_records`` uses a bigserial primary key and is indexed only on what is actually
  aggregated by (time, key, model). It grows at request volume, like gpu_metrics.
* ``models.parameter_count`` and ``model_files.size_bytes`` are BIGINT: a 235B parameter
  count and a multi-gigabyte shard both overflow a 32-bit int.
* ``model_files.sha256`` is nullable by design — hashing a 60 GiB shard takes minutes, so
  verification is opt-in per import.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "59d310bc136b"
down_revision: str | None = "c94a7bea2551"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("architecture", sa.String(length=64), nullable=True),
        sa.Column("parameter_count", sa.BigInteger(), nullable=True),
        sa.Column("quantization", sa.String(length=32), nullable=True),
        sa.Column("context_length", sa.Integer(), nullable=True),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column("runtime", sa.String(length=32), nullable=False),
        sa.Column("required_gpu_memory_mib", sa.Integer(), nullable=True),
        sa.Column("min_gpu_count", sa.Integer(), nullable=False),
        sa.Column("supported_gpu", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("status_detail", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('REGISTERED','AVAILABLE','UNAVAILABLE','DISABLED')",
            name=op.f("ck_models_status_valid"),
        ),
        sa.CheckConstraint(
            "type IN ('LLM','EMBEDDING','RERANKER','ASR','TTS','OCR','VISION','MULTIMODAL')",
            name=op.f("ck_models_type_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
    )
    op.create_index(op.f("ix_models_name"), "models", ["name"], unique=True)
    op.create_index(op.f("ix_models_status"), "models", ["status"], unique=False)
    op.create_index(op.f("ix_models_type"), "models", ["type"], unique=False)
    op.create_table(
        "api_clients",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_api_clients_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_clients")),
        sa.UniqueConstraint("name", name=op.f("uq_api_clients_name")),
    )
    op.create_table(
        "model_aliases",
        sa.Column("alias", sa.String(length=128), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_model_aliases_model_id_models"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_aliases")),
    )
    op.create_index(op.f("ix_model_aliases_alias"), "model_aliases", ["alias"], unique=True)
    op.create_table(
        "model_deployments",
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("state_detail", sa.Text(), nullable=True),
        sa.Column("gpu_indices", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reservation_id", sa.UUID(), nullable=True),
        sa.Column("runtime", sa.String(length=32), nullable=False),
        sa.Column("image", sa.String(length=512), nullable=False),
        sa.Column("container_id", sa.String(length=64), nullable=True),
        sa.Column("container_name", sa.String(length=255), nullable=True),
        sa.Column("internal_port", sa.Integer(), nullable=False),
        sa.Column("internal_url", sa.String(length=512), nullable=True),
        sa.Column("tensor_parallel_size", sa.Integer(), nullable=False),
        sa.Column("max_model_len", sa.Integer(), nullable=True),
        sa.Column("gpu_memory_utilization", sa.Float(), nullable=False),
        sa.Column("command", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("environment", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("logs_excerpt", sa.Text(), nullable=True),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("healthy_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "gpu_memory_utilization > 0 AND gpu_memory_utilization <= 1",
            name=op.f("ck_model_deployments_gpu_memory_fraction"),
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_model_deployments_model_id_models"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
            name=op.f("fk_model_deployments_node_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_model_deployments_requested_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_deployments")),
    )
    op.create_index(
        "ix_model_deployments_model_state", "model_deployments", ["model_id", "state"], unique=False
    )
    op.create_index(
        op.f("ix_model_deployments_reservation_id"),
        "model_deployments",
        ["reservation_id"],
        unique=False,
    )
    op.create_index("ix_model_deployments_state", "model_deployments", ["state"], unique=False)
    op.create_table(
        "model_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("relative_path", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_model_files_model_id_models"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_files")),
        sa.UniqueConstraint("model_id", "relative_path", name="model_path"),
    )
    op.create_table(
        "api_keys",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["api_clients.id"],
            name=op.f("fk_api_keys_client_id_api_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_api_keys_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
    )
    op.create_index("ix_api_keys_hash", "api_keys", ["key_hash"], unique=True)
    op.create_table(
        "usage_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("api_key_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("endpoint", sa.String(length=64), nullable=False),
        sa.Column("requested_model", sa.String(length=128), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("deployment_id", sa.UUID(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("streamed", sa.Boolean(), nullable=False),
        sa.Column("client_disconnected", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
            name=op.f("fk_usage_records_api_key_id_api_keys"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_usage_records_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_records")),
    )
    op.create_index(
        "ix_usage_records_key_recorded",
        "usage_records",
        ["api_key_id", "recorded_at"],
        unique=False,
    )
    op.create_index(
        "ix_usage_records_model_recorded", "usage_records", ["model", "recorded_at"], unique=False
    )
    op.create_index("ix_usage_records_recorded", "usage_records", ["recorded_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_records_recorded", table_name="usage_records")
    op.drop_index("ix_usage_records_model_recorded", table_name="usage_records")
    op.drop_index("ix_usage_records_key_recorded", table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index("ix_api_keys_hash", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("model_files")
    op.drop_index("ix_model_deployments_state", table_name="model_deployments")
    op.drop_index(op.f("ix_model_deployments_reservation_id"), table_name="model_deployments")
    op.drop_index("ix_model_deployments_model_state", table_name="model_deployments")
    op.drop_table("model_deployments")
    op.drop_index(op.f("ix_model_aliases_alias"), table_name="model_aliases")
    op.drop_table("model_aliases")
    op.drop_table("api_clients")
    op.drop_index(op.f("ix_models_type"), table_name="models")
    op.drop_index(op.f("ix_models_status"), table_name="models")
    op.drop_index(op.f("ix_models_name"), table_name="models")
    op.drop_table("models")
    # ### end Alembic commands ###
