"""m29 voice sessions messages and events

Revision ID: bf81e9f7329a
Revises: 4668694c1fd1
Create Date: 2026-08-10 17:59:45.190508

Every migration must implement a working ``downgrade``. ``make migrate-roundtrip``
runs upgrade -> downgrade -> upgrade in CI, so an unimplemented downgrade fails the
build rather than being discovered during a rollback at 3am.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "bf81e9f7329a"
down_revision: str | None = "4668694c1fd1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voice_sessions",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("voice", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("turns", sa.Integer(), nullable=False),
        sa.Column("interruptions", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('CREATED','LISTENING','TRANSCRIBING','THINKING','TOOL_EXECUTION','GENERATING','SYNTHESIZING','SPEAKING','INTERRUPTED','COMPLETED','ERROR')",
            name=op.f("ck_voice_sessions_voice_state_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_voice_sessions_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_voice_sessions_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_voice_sessions")),
    )
    op.create_index(
        op.f("ix_voice_sessions_conversation_id"),
        "voice_sessions",
        ["conversation_id"],
        unique=False,
    )
    op.create_index("ix_voice_sessions_state", "voice_sessions", ["state"], unique=False)
    op.create_index(
        "ix_voice_sessions_user_created", "voice_sessions", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "voice_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["voice_sessions.id"],
            name=op.f("fk_voice_events_session_id_voice_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_voice_events")),
    )
    op.create_index("ix_voice_events_session", "voice_events", ["session_id", "id"], unique=False)
    op.create_table(
        "voice_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("audio_seconds", sa.Float(), nullable=True),
        sa.Column("audio_object", sa.String(length=512), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('user','assistant')", name=op.f("ck_voice_messages_voice_role_valid")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["voice_sessions.id"],
            name=op.f("fk_voice_messages_session_id_voice_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_voice_messages")),
    )
    op.create_index(
        "ix_voice_messages_session", "voice_messages", ["session_id", "sequence"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_voice_messages_session", table_name="voice_messages")
    op.drop_table("voice_messages")
    op.drop_index("ix_voice_events_session", table_name="voice_events")
    op.drop_table("voice_events")
    op.drop_index("ix_voice_sessions_user_created", table_name="voice_sessions")
    op.drop_index("ix_voice_sessions_state", table_name="voice_sessions")
    op.drop_index(op.f("ix_voice_sessions_conversation_id"), table_name="voice_sessions")
    op.drop_table("voice_sessions")
    # ### end Alembic commands ###
