"""phase3 end user attribution

Revision ID: aaecdaa216ff
Revises: 59d310bc136b
Create Date: 2026-08-08 08:45:56.625630

Every migration must implement a working ``downgrade``. ``make migrate-roundtrip``
runs upgrade -> downgrade -> upgrade in CI, so an unimplemented downgrade fails the
build rather than being discovered during a rollback at 3am.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "aaecdaa216ff"
down_revision: str | None = "59d310bc136b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default on every NOT NULL addition. Autogenerate omits it, which fails
    # outright against a table that already has rows — and `usage_records` and
    # `api_clients` both do by the time anyone runs this.
    #
    # For `trusted_identity_headers` the default is also the security-relevant choice:
    # every client that already exists must come out of this migration *not* trusted to
    # assert who its traffic belongs to. The flag is granted deliberately, never
    # inherited from a schema change.
    op.add_column(
        "api_clients",
        sa.Column(
            "trusted_identity_headers",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # Fernet-encrypted; nullable because most clients never sign.
    op.add_column(
        "api_clients", sa.Column("identity_jwt_secret_encrypted", sa.Text(), nullable=True)
    )
    op.add_column("usage_records", sa.Column("end_user", sa.String(length=255), nullable=True))
    op.add_column(
        "usage_records",
        sa.Column("end_user_trusted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # Partial: only rows carrying an end user are ever aggregated on this axis, and on a
    # high-volume table indexing the NULLs would be most of it for nothing.
    op.create_index(
        "ix_usage_records_end_user_recorded",
        "usage_records",
        ["end_user", "recorded_at"],
        unique=False,
        postgresql_where=sa.text("end_user IS NOT NULL"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_records_end_user_recorded", table_name="usage_records")
    op.drop_column("usage_records", "end_user_trusted")
    op.drop_column("usage_records", "end_user")
    op.drop_column("api_clients", "identity_jwt_secret_encrypted")
    op.drop_column("api_clients", "trusted_identity_headers")
    # ### end Alembic commands ###
