"""phase6: api key scopes and rotation

Revision ID: c51dbd2c2471
Revises: 97d0216ff730
Create Date: 2026-08-09 18:48:10.156934

Every migration must implement a working ``downgrade``. ``make migrate-roundtrip``
runs upgrade -> downgrade -> upgrade in CI, so an unimplemented downgrade fails the
build rather than being discovered during a rollback at 3am.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c51dbd2c2471"
down_revision: str | None = "97d0216ff730"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: autogenerate emitted a NOT NULL column with no
    # default, which fails on any database that already has keys — i.e. every real one.
    # '[]' is also the correct value for them: a key minted before scopes existed is
    # unrestricted, and empty means unrestricted.
    op.add_column(
        "api_keys",
        sa.Column(
            "scopes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    op.add_column("api_keys", sa.Column("rotated_to", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_api_keys_rotated_to_api_keys"),
        "api_keys",
        "api_keys",
        ["rotated_to"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_api_keys_rotated_to_api_keys"), "api_keys", type_="foreignkey")
    op.drop_column("api_keys", "rotated_to")
    op.drop_column("api_keys", "scopes")
    # ### end Alembic commands ###
