"""phase6: external deployments have no node

Revision ID: 388b8e077abc
Revises: 49981d3780de
Two changes, both required for an **external** runtime — one the platform points at
rather than starts (Ollama, or any other already-running OpenAI-compatible server):

* models.endpoint_url — where that server already serves the model. Null for
  everything the platform deploys itself, where the address belongs to the container
  the platform created.
* model_deployments.node_id becomes nullable. An external runtime runs somewhere
  the platform has no node record for. Widening a NOT NULL is safe in both directions
  here because no existing row has a null.

Create Date: 2026-08-08 20:34:01.628293

Every migration must implement a working ``downgrade``. ``make migrate-roundtrip``
runs upgrade -> downgrade -> upgrade in CI, so an unimplemented downgrade fails the
build rather than being discovered during a rollback at 3am.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "388b8e077abc"
down_revision: str | None = "49981d3780de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("model_deployments", "node_id", existing_type=sa.UUID(), nullable=True)
    op.add_column("models", sa.Column("endpoint_url", sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # **This deletes external deployments**, and that is the only correct option rather
    # than a convenience.
    #
    # A null node_id is not a missing value here — it is the whole meaning of the row:
    # the workload runs somewhere the platform has no node record for. The old schema has
    # no way to express that, so there is nothing to migrate these rows *to*. Inventing a
    # node to point at would be worse: it would claim the platform manages a workload it
    # has never touched.
    #
    # The loss is small and recoverable by design. An external deployment holds no
    # scheduling state and reserves no GPUs — re-attaching is one API call against a
    # runtime that never stopped serving. The models themselves survive; only the rows
    # saying "we point at this" are removed.
    op.execute("DELETE FROM model_deployments WHERE node_id IS NULL")
    op.drop_column("models", "endpoint_url")
    op.alter_column("model_deployments", "node_id", existing_type=sa.UUID(), nullable=False)
